export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

export const CREATE_TOKEN_REQUEST = "CREATE_TOKEN_REQUEST"
export const CREATE_TOKEN_SUCCESS = "CREATE_TOKEN_SUCCESS"
export const CREATE_TOKEN_FAIL = "CREATE_TOKEN_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const CREATE_URL_REQUEST = "CREATE_URL_REQUEST"
export const CREATE_URL_SUCCESS = "CREATE_URL_SUCCESS"
export const CREATE_URL_FAIL = "CREATE_URL_FAIL"

export const FETCH_URL_REQUEST = "FETCH_URL_REQUEST"
export const FETCH_URL_SUCCESS = "FETCH_URL_SUCCESS"
export const FETCH_URL_FAIL = "FETCH_URL_FAIL"

export const USER_LOGOUT ="USER_LOGOUT"